# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: tfsec-sarif

on:
  workflow_dispatch:

jobs:
  tfsec:
    name: Run tfsec and generate sarif report
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #tag=4.0.0

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 #tag=0.1.4
        with:
          tfsec_version: "v1.28.2"
          sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd #tag=codeql-bundle-20220421
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
